baseURL = "https://lazada-one.netlify.app"
languageCode = "en-us"
title = "Lazada One Data Portfolio & Blog"
theme = "data-science"
disqusShortname = "lazadaone"
enableEmoji = true
# allow search engines to search/crawl everything
enableRobotsTXT = true

preserveTaxonomyNames = true

# sectionPagesMenu = "main"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  author = "Lazada One"
  description = "A collection of my data science projects and blog posts about R, d3, and everything in between."
  twitterAuthor = "@lazadaone"
  twitterSite = "@lazadaone"
  images = ['logo.jpg']

  # options for highlight.js (version, additional languages, and theme)
  highlight = true
  highlightjsVersion = "9.15.6"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml", "javascript"]
  custom = true
  highlightjsThemeLight = ""
  highlightjsThemeDark = ""

  #email = "mailto:AmberThomasMSc@gmail.com"
  #twitter = "https://twitter.com/ProQuesAsker"
  #github = "https://www.github.com/ProQuestionAsker"
  #linkedin = "https://www.linkedin.com/in/amberrthomas/"



[params.social]
  email = "mailto:lazadaone@gmail.com"
  twitter = "https://twitter.com/lazadaone"
  github = "https://www.github.com/lazadaone"
  linkedin = "https://www.linkedin.com/in/lazadaone/"
  stackoverflow = ""
  facebook = ""
  instagram = ""
  dribbble = ""
  kaggle = ""
  medium = ""
  patreon = ""
  pinterest = ""
  youtube = ""
